version: '3.7'

services:
  app1:
    build: ./app
    ports:
      - "8001:8000"
    environment:
      - APP_VERSION=v1.0
    volumes:
      - ./app:/usr/src/app

  app2:
    build: ./app
    ports:
      - "8002:8000"
    environment:
      - APP_VERSION=v1.0
    volumes:
      - ./app:/usr/src/app

  app3:
    build: ./app
    ports:
      - "8003:8000"
    environment:
      - APP_VERSION=v1.0
    volumes:
      - ./app:/usr/src/app

  prometheus:
    image: prom/prometheus:v2.47.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.rules.yml:/etc/prometheus/alerts.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  alertmanager:
    image: prom/alertmanager:v0.26.0
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  agent:
    build: ./agent
    ports:
      - "8080:8080"
    env_file:
      - ./agent/.env
