route:
  receiver: 'discord-webhook'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'discord-webhook'
    webhook_configs:
      - url: 'http://agent:8080/webhook'
        send_resolved: true
