model_list:
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4
      api_key: os.environ/OPENAI_API_KEY
  - model_name: claude-2
    litellm_params:
      model: anthropic/claude-2
      api_key: os.environ/ANTHROPIC_API_KEY

litellm_settings:
  # Sets the fallback logic
  fallbacks:
    - gpt-4:
      - claude-2
  # Enables a /health endpoint for monitoring
  health_check: True
